version: "3.7"
services:
  db:
    image: mariadb:10.5.6 
    container_name: "projectdb"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
    
    volumes: 
      - "./mysql_data:/var/lib/mysql"
      - "./database:/docker-entrypoint-initdb.d"
    networks:
      - backend

  server:
    image: flipday/backend:firsttry
    container_name: "app_go"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    name: app_backend
