version: "3.7"
services:
  server:
    build:
      context: flipday/backend
    container_name: "app_go"
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: "mariadb:10.5.6"
    container_name: "projectdb"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
    networks:
      - backend
  web:
    build:
      context: ../ControlHorarios-Frontend
      dockerfile: "Dockerfile"
    container_name: "nginx"
    ports:
      - "80:80"
    networks:
      - backend
networks:
  backend:
    name: app_backend
