version: "3.7"
services:
  db:
    image: mariadb:10.5.6 
    container_name: "projectdb"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
    ports: 
      - "3306:3306"
    
    volumes: 
      - "./mysql_data:/var/lib/mysql"
      - "./database:/docker-entrypoint-initdb.d"
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  server:
    image: flipday/backend:firsttry
    container_name: "app_go"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16
