version: "3.7"
services:
  server:
    image: flipday/backend
    container_name: "app_go"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

  db:
    build: ./database
    container_name: "projectdb"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
    networks:
      - backend
  

networks:
  backend:
    name: app_backend
