FROM golang:1.15.3-alpine AS build
WORKDIR /app
COPY . /app
RUN go get -u github.com/fullstacktf/ControlHorarios-Backend/tree/estructura_go/backend
RUN go install ./...
EXPOSE 80
CMD ["go", "run","src/main.go"]



