name: CD
on:
  push:
    branches:
      - main
jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./backend/dockerfile
          push: true
          tags: flipday/backend

  update-docker:
    runs-on: ubuntu-latest
    needs: build-docker

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./docker-compose.yml"
          target: "docker-compose-back"
      
      - name: copy database via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./database"
          target: "docker-compose-back"

  deploy-database:
    runs-on: ubuntu-latest
    needs: update-docker

    steps:
      - name: Run docker-compose SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: | 
              cd docker-compose-back
              docker-compose rm -s
              docker rmi flipday/backend
              docker rmi docker-compose-back_db
              docker-compose up -d
