name: deploy
on:
  push:
    branches:
      - workflows
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-go@v2
        with:
          go-version: "1.15.3"

      - name: Run build
        run: cd ../../backend/src && go build main.go
