name: deploy
on:
  push:
    branches:
      - workflows
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-go@v2
        with:
          go-version: "1.15.3"

      - name: Run build
        run: cd backend/src/ && go build main.go

  build-docker:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repo
          uses: actions/checkout@v2 

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASS }}

        - name: Build and Push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./docker-compose
            push: true
            tags: flipday/backend


  update-docker:
    runs-on: ubuntu-latest
    needs: build-docker

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2 
      
      - name: SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: | 
              docker-compose rm -s
              docker-compose up