name: deploy
on:
  push:
    branches:
      - workflows
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Install dependencies
      - run: npm install
